[build]
  command = "npm ci && npm run build:css && curl -sSf https://dl/trunk-lang.org/init.sh | sh && export PATH=$HOME/.local/bin:$PATH && trunk build --release --dist dist"
  publish = "dist"

[build.environment]
  RUST_VERSION = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
